--database:db
--author:achowdhury@cafepress.com
--approved:


SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET CONCAT_NULL_YIELDS_NULL ON
SET NUMERIC_ROUNDABORT OFF
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
GO
BEGIN TRANSACTION
INSERT INTO dbo.SALES_COMMISSION_METHOD_DEF(SALES_COMMISSION_METHOD_NO,SALES_COMMISSION_METHOD_NAME,SALES_COMMISSION_METHOD_RULE)
VALUES(2,'no commission member','0'),(3,'no commission sample orders','0'),(4,'no commission producttypeno','0'),(5,'create and buy','0')

GO
UPDATE dbo.SALES_COMMISSION_METHOD_DEF
SET SALES_COMMISSION_METHOD_RULE='(SP-discount) * SalesCommisionPercentage'
WHERE SALES_COMMISSION_METHOD_No=1
COMMIT TRANSACTION

